### ISSUE TITLE
New build for Linux/amd64

### ISSUE THREAD

**Issue by corsac-s** [aussig/XAddonManager#3]
Hi,

it seems that latest released version (2.0.0) is nearly 4 years old. Would it be possible to make a new release, and make a build targeting x86_64?

At first I wanted to build the stuff myself, but it seems that you need Xojo which is commercial, unfortunately.

**Comment by aussig** [comment]
I haven't really worked on this for a while as xOrganiser seems to have taken over. However, I guess this might still be useful for Linux and Mac users so I've built you a [new release here](https://github.com/aussig/XAddonManager/releases/latest).

**Comment by corsac-s** [comment]
Many thanks for taking the time.

It seems to start, I get a GTK window for selecting my X-Plane folder, but after that nothing happens. Not sure how to debug that.

**Comment by aussig** [comment]
Can I ask how long you left it?

When XAM was first written X-Plane didn't include Global Airports in the Custom Scenery folder.  As these are a huge set of DSFs, it can take a long time to parse.  So it's possible that it's taking a while?

As a test, you could temporarily remove Global Airports from Custom Scenery and see whether XAM works.

I probably need to review the code to make sure it's as efficient as possible, and put a progress bar on screen. I've created an issue for this: #4

**Comment by corsac-s** [comment]
> Can I ask how long you left it?
> 
> When XAM was first written X-Plane didn't include Global Airports in the Custom Scenery folder. As these are a huge set of DSFs, it can take a long time to parse. So it's possible that it's taking a while?

Indeed, I've let it run a bit and it did ended showing the interface. Thanks!
